[package]
name = "roosterscript5"
version = "0.1.0"
authors = ["bobismijnnaam <bobrubbens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
cursive = "0.14.0"
num = "0.2.1"
